# !!! IMPORTANT : MODIFIEZ CE FICHIER POUR CHAQUE NOUVEAU PROJET !!!
# Adaptez le nom, la description, la version et les dépendances selon vos besoins.

name: swiftyprotein # !!! IMPORTANT : CHANGER LE NOM DU PROJET !!!
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.jpg # !!! IMPORTANT : AJOUTEZ/ADAPTEZ VOS ASSETS ICI.
